-- ═══════════════════════════════════════════════
-- CODEHERWAY SUPABASE SCHEMA
-- Run this in Supabase SQL Editor (one time)
-- ═══════════════════════════════════════════════

-- 1. User Profiles (extends Supabase auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  display_name text check (char_length(display_name) <= 60),
  avatar_url text check (char_length(avatar_url) <= 500),
  created_at timestamptz default now()
);

-- 2. Progress — completed lessons + quiz scores
create table if not exists public.progress (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  lesson_key text not null,
  completed_at timestamptz default now(),
  unique(user_id, lesson_key)
);

create table if not exists public.quiz_scores (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  quiz_key text not null,
  score text not null,
  completed_at timestamptz default now(),
  unique(user_id, quiz_key)
);

-- 3. XP
create table if not exists public.xp (
  user_id uuid references auth.users on delete cascade primary key,
  total integer default 0,
  updated_at timestamptz default now()
);

-- 4. Streaks
create table if not exists public.streaks (
  user_id uuid references auth.users on delete cascade primary key,
  days integer default 0,
  last_date date,
  updated_at timestamptz default now()
);

-- 5. Daily Goals
create table if not exists public.daily_goals (
  user_id uuid references auth.users on delete cascade primary key,
  goal_date date default current_date,
  count integer default 0,
  updated_at timestamptz default now()
);

-- 6. Earned Badges
create table if not exists public.badges (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  badge_id text not null,
  earned_at timestamptz default now(),
  unique(user_id, badge_id)
);

-- 7. Spaced Repetition Queue
create table if not exists public.sr_cards (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  question text not null,
  code text,
  options jsonb not null,
  correct integer not null,
  explanation text not null,
  source text not null,
  added_at timestamptz default now(),
  next_review timestamptz default now(),
  interval_days integer default 1,
  ease real default 2.5,
  unique(user_id, question)
);

-- 8. Bookmarks (NEW)
create table if not exists public.bookmarks (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  lesson_key text not null,
  course_id text not null,
  lesson_title text not null,
  created_at timestamptz default now(),
  unique(user_id, lesson_key)
);

-- 9. Notes (NEW)
create table if not exists public.notes (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  lesson_key text not null,
  content text not null check (char_length(content) <= 10000),
  updated_at timestamptz default now(),
  unique(user_id, lesson_key)
);

-- 10. Courses Visited (for Explorer badge)
create table if not exists public.courses_visited (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  course_id text not null,
  visited_at timestamptz default now(),
  unique(user_id, course_id)
);

-- 11. Last Position (resume where you left off)
create table if not exists public.last_position (
  user_id uuid references auth.users on delete cascade primary key,
  course text,
  mod text,
  les text,
  updated_at timestamptz default now()
);

-- 12. Product analytics events (onboarding, lesson flow, etc.)
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  event_name text not null check (char_length(event_name) <= 80),
  path text not null default '/' check (char_length(path) <= 300),
  payload jsonb not null default '{}'::jsonb,
  source text not null default 'web',
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- ═══════════════════════════════════════════════
-- ROW LEVEL SECURITY — users can only see their own data
-- ═══════════════════════════════════════════════

alter table public.profiles enable row level security;
alter table public.progress enable row level security;
alter table public.quiz_scores enable row level security;
alter table public.xp enable row level security;
alter table public.streaks enable row level security;
alter table public.daily_goals enable row level security;
alter table public.badges enable row level security;
alter table public.sr_cards enable row level security;
alter table public.bookmarks enable row level security;
alter table public.notes enable row level security;
alter table public.courses_visited enable row level security;
alter table public.last_position enable row level security;
alter table public.analytics_events enable row level security;

-- Policy: users can CRUD their own rows
create policy "Users manage own profiles" on public.profiles for all using (auth.uid() = id);
create policy "Users manage own progress" on public.progress for all using (auth.uid() = user_id);
create policy "Users manage own quiz_scores" on public.quiz_scores for all using (auth.uid() = user_id);
create policy "Users manage own xp" on public.xp for all using (auth.uid() = user_id);
create policy "Users manage own streaks" on public.streaks for all using (auth.uid() = user_id);
create policy "Users manage own daily_goals" on public.daily_goals for all using (auth.uid() = user_id);
create policy "Users manage own badges" on public.badges for all using (auth.uid() = user_id);
create policy "Users manage own sr_cards" on public.sr_cards for all using (auth.uid() = user_id);
create policy "Users manage own bookmarks" on public.bookmarks for all using (auth.uid() = user_id);
create policy "Users manage own notes" on public.notes for all using (auth.uid() = user_id);
create policy "Users manage own courses_visited" on public.courses_visited for all using (auth.uid() = user_id);
create policy "Users manage own last_position" on public.last_position for all using (auth.uid() = user_id);
create policy "Users insert own analytics events"
  on public.analytics_events
  for insert
  with check (auth.uid() = user_id);

-- Auto-create profile + XP + streak rows on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, display_name) values (new.id, new.raw_user_meta_data->>'display_name');
  insert into public.xp (user_id) values (new.id);
  insert into public.streaks (user_id) values (new.id);
  insert into public.daily_goals (user_id) values (new.id);
  insert into public.last_position (user_id) values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Indexes for performance
create index if not exists idx_progress_user on public.progress(user_id);
create index if not exists idx_quiz_scores_user on public.quiz_scores(user_id);
create index if not exists idx_badges_user on public.badges(user_id);
create index if not exists idx_sr_cards_user_review on public.sr_cards(user_id, next_review);
create index if not exists idx_bookmarks_user on public.bookmarks(user_id);
create index if not exists idx_notes_user on public.notes(user_id);
create index if not exists idx_analytics_events_user_occurred
  on public.analytics_events(user_id, occurred_at desc);
create index if not exists idx_analytics_events_name_occurred
  on public.analytics_events(event_name, occurred_at desc);

-- ═══════════════════════════════════════════════
-- ADMIN SUPPORT
-- ═══════════════════════════════════════════════

-- Add is_admin flag to profiles
alter table public.profiles add column if not exists is_admin boolean default false;

-- Admin can read all user data (RLS policies)
-- Run this AFTER setting your account's is_admin = true

create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  );
end;
$$ language plpgsql security definer;

create policy "Admins read all analytics events"
  on public.analytics_events
  for select
  using (is_admin());

-- Admin read policies (admins can SELECT all rows)
create policy "Admins read all profiles" on public.profiles for select using (is_admin());
create policy "Admins read all progress" on public.progress for select using (is_admin());
create policy "Admins read all quiz_scores" on public.quiz_scores for select using (is_admin());
create policy "Admins read all xp" on public.xp for select using (is_admin());
create policy "Admins read all streaks" on public.streaks for select using (is_admin());
create policy "Admins read all badges" on public.badges for select using (is_admin());

-- Admin user table with pre-aggregated user stats.
create or replace view public.admin_user_rollups as
select
  p.id,
  p.display_name,
  p.is_admin,
  p.is_disabled,
  p.created_at,
  coalesce(progress_counts.lessons_done, 0)::int as lessons_done,
  coalesce(x.total, 0)::int as xp_total,
  coalesce(s.days, 0)::int as streak_days,
  coalesce(badge_counts.badges_earned, 0)::int as badges_earned
from public.profiles p
left join (
  select user_id, count(*)::int as lessons_done
  from public.progress
  group by user_id
) progress_counts on progress_counts.user_id = p.id
left join public.xp x on x.user_id = p.id
left join public.streaks s on s.user_id = p.id
left join (
  select user_id, count(*)::int as badges_earned
  from public.badges
  group by user_id
) badge_counts on badge_counts.user_id = p.id;

grant select on public.admin_user_rollups to authenticated;

create or replace function public.admin_dashboard_metrics()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payload jsonb;
begin
  if not public.is_admin() then
    raise exception 'Admin privileges required';
  end if;

  with
  users_total as (
    select count(*)::int as value from public.profiles
  ),
  users_week as (
    select count(*)::int as value
    from public.profiles
    where created_at >= now() - interval '7 days'
  ),
  users_month as (
    select count(*)::int as value
    from public.profiles
    where created_at >= now() - interval '30 days'
  ),
  active_week as (
    select count(distinct user_id)::int as value
    from public.progress
    where completed_at >= now() - interval '7 days'
  ),
  completions as (
    select count(*)::int as value from public.progress
  ),
  quiz_attempts as (
    select count(*)::int as value from public.quiz_scores
  ),
  badges_total as (
    select count(*)::int as value from public.badges
  ),
  xp_total as (
    select coalesce(sum(total), 0)::bigint as value from public.xp
  ),
  top_users as (
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'user_id', top.user_id,
          'total', top.total,
          'name', coalesce(p.display_name, 'Anonymous')
        )
        order by top.total desc
      ),
      '[]'::jsonb
    ) as value
    from (
      select user_id, total
      from public.xp
      order by total desc
      limit 10
    ) top
    left join public.profiles p on p.id = top.user_id
  ),
  funnel_7d as (
    select jsonb_build_object(
      'onboardingOpened', count(*) filter (where event_name = 'onboarding_opened'),
      'onboardingAdvanced', count(*) filter (where event_name = 'onboarding_step_next'),
      'onboardingClosed', count(*) filter (where event_name = 'onboarding_closed'),
      'lessonViewed', count(*) filter (where event_name = 'lesson_viewed'),
      'lessonCompleted', count(*) filter (
        where event_name = 'lesson_completion_toggled'
          and coalesce(payload->>'completionState', '') = 'marked_complete'
      ),
      'lessonNextClicked', count(*) filter (where event_name = 'lesson_next_clicked')
    ) as value
    from public.analytics_events
    where occurred_at >= now() - interval '7 days'
  ),
  funnel_30d as (
    select jsonb_build_object(
      'onboardingOpened', count(*) filter (where event_name = 'onboarding_opened'),
      'onboardingAdvanced', count(*) filter (where event_name = 'onboarding_step_next'),
      'onboardingClosed', count(*) filter (where event_name = 'onboarding_closed'),
      'lessonViewed', count(*) filter (where event_name = 'lesson_viewed'),
      'lessonCompleted', count(*) filter (
        where event_name = 'lesson_completion_toggled'
          and coalesce(payload->>'completionState', '') = 'marked_complete'
      ),
      'lessonNextClicked', count(*) filter (where event_name = 'lesson_next_clicked')
    ) as value
    from public.analytics_events
    where occurred_at >= now() - interval '30 days'
  )
  select jsonb_build_object(
    'totalUsers', users_total.value,
    'newUsersWeek', users_week.value,
    'newUsersMonth', users_month.value,
    'activeUsersWeek', active_week.value,
    'totalCompletions', completions.value,
    'totalQuizAttempts', quiz_attempts.value,
    'totalBadges', badges_total.value,
    'totalXP', xp_total.value,
    'topUsers', top_users.value,
    'funnel7d', funnel_7d.value,
    'funnel30d', funnel_30d.value
  )
  into v_payload
  from users_total, users_week, users_month, active_week, completions,
       quiz_attempts, badges_total, xp_total, top_users, funnel_7d, funnel_30d;

  return v_payload;
end;
$$;

revoke all on function public.admin_dashboard_metrics() from public;
grant execute on function public.admin_dashboard_metrics() to authenticated;

-- Pre-aggregated analytics snapshots for lightweight reporting.
drop materialized view if exists public.analytics_daily_funnel;
create materialized view public.analytics_daily_funnel as
select
  date_trunc('day', occurred_at)::date as day,
  count(*) filter (where event_name = 'onboarding_opened')::int as onboarding_opened,
  count(*) filter (where event_name = 'onboarding_step_next')::int as onboarding_advanced,
  count(*) filter (where event_name = 'onboarding_closed')::int as onboarding_closed,
  count(*) filter (where event_name = 'lesson_viewed')::int as lesson_viewed,
  count(*) filter (
    where event_name = 'lesson_completion_toggled'
      and coalesce(payload->>'completionState', '') = 'marked_complete'
  )::int as lesson_completed,
  count(*) filter (where event_name = 'lesson_next_clicked')::int as lesson_next_clicked
from public.analytics_events
group by 1
with no data;

create unique index if not exists idx_analytics_daily_funnel_day
  on public.analytics_daily_funnel(day);

create or replace function public.refresh_analytics_daily_funnel(
  p_days_back integer default 180
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin privileges required';
  end if;

  -- Full refresh keeps logic simple and deterministic. p_days_back is
  -- retained so we can later move to incremental refresh without
  -- changing the function contract used by API clients.
  perform p_days_back;
  refresh materialized view public.analytics_daily_funnel;
end;
$$;

create or replace function public.get_analytics_daily_funnel(
  p_days integer default 30
) returns table (
  day date,
  onboarding_opened integer,
  onboarding_advanced integer,
  onboarding_closed integer,
  lesson_viewed integer,
  lesson_completed integer,
  lesson_next_clicked integer
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin privileges required';
  end if;

  return query
  select
    f.day,
    f.onboarding_opened,
    f.onboarding_advanced,
    f.onboarding_closed,
    f.lesson_viewed,
    f.lesson_completed,
    f.lesson_next_clicked
  from public.analytics_daily_funnel f
  where f.day >= current_date - (greatest(p_days, 1) - 1)
  order by f.day desc;
end;
$$;

revoke all on function public.refresh_analytics_daily_funnel(integer) from public;
grant execute on function public.refresh_analytics_daily_funnel(integer) to authenticated;

revoke all on function public.get_analytics_daily_funnel(integer) from public;
grant execute on function public.get_analytics_daily_funnel(integer) to authenticated;

-- Suggested production strategy: use pg_cron or a Netlify scheduled
-- function to call refresh_analytics_daily_funnel() on a fixed cadence.

-- To bootstrap the FIRST admin, run in Supabase SQL Editor (uses the
-- postgres role, which bypasses the trigger added below):
--   UPDATE public.profiles SET is_admin = true WHERE id = 'YOUR-USER-UUID-HERE';
-- Subsequent admin changes MUST go through public.set_user_admin() (see below).

-- Add is_disabled flag to profiles
alter table public.profiles add column if not exists is_disabled boolean default false;

-- Admins can update profiles (to disable/enable users). The trigger
-- defined below blocks any UPDATE that would change is_admin via this
-- broad policy — so admins can flip is_disabled freely but cannot
-- escalate themselves or anyone else without going through the
-- set_user_admin() RPC.
create policy "Admins update all profiles" on public.profiles for update using (is_admin());

-- ═══════════════════════════════════════════════
-- ADMIN ESCALATION GUARD
-- ═══════════════════════════════════════════════
--
-- Problem: the "Admins update all profiles" policy above lets any admin
-- run `UPDATE profiles SET is_admin = true WHERE id = ...` on ANY row,
-- including their own. One compromised admin = permanent platform
-- takeover. Below we:
--   1. Block direct edits to the is_admin column from the REST API.
--   2. Force admin promotion/demotion through a SECURITY DEFINER RPC
--      that refuses self-edits and writes an audit log row.

create table if not exists public.admin_audit_log (
  id uuid default gen_random_uuid() primary key,
  actor_id uuid not null,
  target_id uuid not null,
  action text not null,
  details jsonb,
  created_at timestamptz default now()
);

alter table public.admin_audit_log enable row level security;

create policy "Admins read audit log" on public.admin_audit_log
  for select using (is_admin());

-- Trigger: refuse any UPDATE that flips is_admin unless the change is
-- explicitly sanctioned by set_user_admin() (which sets a session flag)
-- or comes from a database superuser running raw SQL (migrations,
-- bootstrap, the initial admin).
create or replace function public.guard_profile_admin_changes()
returns trigger
language plpgsql
as $$
begin
  if new.is_admin is distinct from old.is_admin then
    -- Allow if explicitly sanctioned by set_user_admin().
    if coalesce(current_setting('app.bypass_admin_guard', true), 'false') = 'true' then
      return new;
    end if;
    -- Allow superuser / migrations (Supabase SQL Editor).
    if current_user in ('postgres', 'supabase_admin') then
      return new;
    end if;
    raise exception 'is_admin can only be changed via public.set_user_admin()';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_guard_profile_admin_changes on public.profiles;
create trigger trg_guard_profile_admin_changes
  before update of is_admin on public.profiles
  for each row execute function public.guard_profile_admin_changes();

-- Sanctioned RPC for promoting/demoting admins. Refuses self-edits.
create or replace function public.set_user_admin(
  target_user_id uuid,
  make_admin boolean
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caller uuid := auth.uid();
begin
  if v_caller is null then
    raise exception 'Authentication required';
  end if;
  if not public.is_admin() then
    raise exception 'Admin privileges required';
  end if;
  if v_caller = target_user_id then
    raise exception 'Admins cannot change their own is_admin flag';
  end if;

  -- Sanction the change for the trigger above, then immediately clear
  -- the flag so it can't leak into other statements in the same tx.
  perform set_config('app.bypass_admin_guard', 'true', true);
  update public.profiles set is_admin = make_admin where id = target_user_id;
  perform set_config('app.bypass_admin_guard', 'false', true);

  insert into public.admin_audit_log (actor_id, target_id, action, details)
  values (
    v_caller,
    target_user_id,
    case when make_admin then 'grant_admin' else 'revoke_admin' end,
    jsonb_build_object('make_admin', make_admin)
  );
end;
$$;

revoke all on function public.set_user_admin(uuid, boolean) from public;
grant execute on function public.set_user_admin(uuid, boolean) to authenticated;

-- ═══════════════════════════════════════════════
-- AI RATE LIMITING
-- ═══════════════════════════════════════════════
--
-- Replaces the in-memory rate limit in netlify/functions/ai.js, which
-- resets on every cold start and isn't shared across concurrent
-- function instances.
--
-- The Netlify function calls public.consume_ai_quota() with the user's
-- bearer token; the function reads auth.uid() server-side so callers
-- can't spoof another user. Limits are HARDCODED inside the function
-- so authenticated callers can't pass a higher cap.

create table if not exists public.ai_rate_limits (
  user_id uuid references auth.users on delete cascade primary key,
  window_start timestamptz not null default now(),
  count integer not null default 0
);

alter table public.ai_rate_limits enable row level security;
-- No CRUD policies — only the SECURITY DEFINER function below can
-- read or write this table from the REST API.

create or replace function public.consume_ai_quota()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_max constant integer := 10;        -- 10 requests
  v_window constant integer := 60;     -- per 60 seconds
  v_now timestamptz := now();
  v_count integer;
begin
  if v_user is null then
    return false;
  end if;

  insert into public.ai_rate_limits (user_id, window_start, count)
  values (v_user, v_now, 1)
  on conflict (user_id) do update
    set window_start = case
          when public.ai_rate_limits.window_start < v_now - make_interval(secs => v_window)
            then v_now
          else public.ai_rate_limits.window_start
        end,
        count = case
          when public.ai_rate_limits.window_start < v_now - make_interval(secs => v_window)
            then 1
          else public.ai_rate_limits.count + 1
        end
  returning count into v_count;

  return v_count <= v_max;
end;
$$;

revoke all on function public.consume_ai_quota() from public;
grant execute on function public.consume_ai_quota() to authenticated;

-- ═══════════════════════════════════════════════
-- PUBLIC PROFILE PAGES  (/u/:handle)
-- ═══════════════════════════════════════════════
--
-- Lets a learner opt in to a read-only public page
-- showing their display name, XP, streak, lesson
-- count, and badge count. Opt-in defaults to false;
-- everything else stays private.
--
-- Design: we DON'T add a public RLS policy directly
-- to `profiles`, `xp`, `streaks`, etc. (that would
-- risk over-exposing columns). Instead we create a
-- `public_profiles` VIEW that projects only the
-- fields we want public, and grant SELECT on that
-- view to `anon`.

alter table public.profiles
  add column if not exists is_public boolean default false;
alter table public.profiles
  add column if not exists public_handle text unique
    check (public_handle ~ '^[a-z0-9_-]{3,30}$');
-- ^ Enforce URL-safe lowercase handles: 3-30 chars, alphanumeric/dash/underscore only.

-- Case-insensitive handle lookup (so /u/Jenna and /u/jenna both work).
create index if not exists idx_profiles_public_handle_lower
  on public.profiles (lower(public_handle))
  where is_public = true;

create or replace view public.public_profiles as
select
  p.id                    as id,
  p.display_name          as display_name,
  p.avatar_url            as avatar_url,
  p.public_handle         as handle,
  coalesce(x.total, 0)    as xp_total,
  coalesce(s.days, 0)     as streak_days,
  coalesce(lesson_counts.n, 0) as lessons_completed,
  coalesce(badge_counts.n, 0)  as badges_earned
from public.profiles p
left join public.xp x on x.user_id = p.id
left join public.streaks s on s.user_id = p.id
left join (
  select user_id, count(*)::int as n
  from public.progress
  group by user_id
) lesson_counts on lesson_counts.user_id = p.id
left join (
  select user_id, count(*)::int as n
  from public.badges
  group by user_id
) badge_counts on badge_counts.user_id = p.id
where p.is_public = true
  and coalesce(p.is_disabled, false) = false;

-- Views inherit RLS from their base tables, so we also need to grant
-- SELECT on the view itself to the anon role. Base-table RLS continues
-- to protect raw rows; only the projected columns above are exposed.
grant select on public.public_profiles to anon, authenticated;

-- And we need a policy on `profiles` that lets `anon` read the specific
-- public columns via the view. Postgres RLS doesn't do column-level
-- grants in a policy, so we add a row-level "is_public = true" policy
-- and rely on the VIEW to limit the columns.
drop policy if exists "Public profiles readable by anyone" on public.profiles;
create policy "Public profiles readable by anyone"
  on public.profiles
  for select
  using (is_public = true and coalesce(is_disabled, false) = false);

-- Same for the joined tables — only the minimum columns projected by
-- the view are reachable, but the base-table RLS still needs a path.
drop policy if exists "Public xp readable" on public.xp;
create policy "Public xp readable"
  on public.xp
  for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = xp.user_id
        and profiles.is_public = true
        and coalesce(profiles.is_disabled, false) = false
    )
  );

drop policy if exists "Public streaks readable" on public.streaks;
create policy "Public streaks readable"
  on public.streaks
  for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = streaks.user_id
        and profiles.is_public = true
        and coalesce(profiles.is_disabled, false) = false
    )
  );

drop policy if exists "Public progress count readable" on public.progress;
create policy "Public progress count readable"
  on public.progress
  for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = progress.user_id
        and profiles.is_public = true
        and coalesce(profiles.is_disabled, false) = false
    )
  );

drop policy if exists "Public badges count readable" on public.badges;
create policy "Public badges count readable"
  on public.badges
  for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = badges.user_id
        and profiles.is_public = true
        and coalesce(profiles.is_disabled, false) = false
    )
  );

-- Users can still only UPDATE their own is_public / public_handle
-- columns through the existing "Users manage own profiles" policy —
-- it uses `auth.uid() = id`, which prevents cross-user toggling.

